export interface CurrencyData {
  code: string
  name: string
  symbol: string
  flag: string
  country: string
}

export const CURRENCY_DATA: CurrencyData[] = [
  { code: "USD", name: "US Dollar", symbol: "$", flag: "🇺🇸", country: "United States" },
  { code: "EUR", name: "Euro", symbol: "€", flag: "🇪🇺", country: "European Union" },
  { code: "GBP", name: "British Pound", symbol: "£", flag: "🇬🇧", country: "United Kingdom" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", flag: "🇯🇵", country: "Japan" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", flag: "🇦🇺", country: "Australia" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", flag: "🇨🇦", country: "Canada" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", flag: "🇨🇭", country: "Switzerland" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", flag: "🇨🇳", country: "China" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", flag: "🇸🇪", country: "Sweden" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", flag: "🇳🇿", country: "New Zealand" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", flag: "🇲🇽", country: "Mexico" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", flag: "🇸🇬", country: "Singapore" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", flag: "🇭🇰", country: "Hong Kong" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", flag: "🇳🇴", country: "Norway" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", flag: "🇰🇷", country: "South Korea" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", flag: "🇹🇷", country: "Turkey" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", flag: "🇷🇺", country: "Russia" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", flag: "🇮🇳", country: "India" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", flag: "🇧🇷", country: "Brazil" },
  { code: "ZAR", name: "South African Rand", symbol: "R", flag: "🇿🇦", country: "South Africa" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", flag: "🇵🇱", country: "Poland" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", flag: "🇩🇰", country: "Denmark" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", flag: "🇨🇿", country: "Czech Republic" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", flag: "🇭🇺", country: "Hungary" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪", flag: "🇮🇱", country: "Israel" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", flag: "🇨🇱", country: "Chile" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", flag: "🇵🇭", country: "Philippines" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", flag: "🇦🇪", country: "United Arab Emirates" },
  { code: "COP", name: "Colombian Peso", symbol: "$", flag: "🇨🇴", country: "Colombia" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", flag: "🇸🇦", country: "Saudi Arabia" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", flag: "🇲🇾", country: "Malaysia" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", flag: "🇷🇴", country: "Romania" },
  { code: "THB", name: "Thai Baht", symbol: "฿", flag: "🇹🇭", country: "Thailand" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", flag: "🇧🇬", country: "Bulgaria" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", flag: "🇭🇷", country: "Croatia" },
  { code: "ISK", name: "Icelandic Krona", symbol: "kr", flag: "🇮🇸", country: "Iceland" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", flag: "🇪🇬", country: "Egypt" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", flag: "🇶🇦", country: "Qatar" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", flag: "🇰🇼", country: "Kuwait" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", flag: "🇧🇭", country: "Bahrain" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", flag: "🇴🇲", country: "Oman" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", flag: "🇯🇴", country: "Jordan" },
  { code: "LBP", name: "Lebanese Pound", symbol: "£", flag: "🇱🇧", country: "Lebanon" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", flag: "🇵🇰", country: "Pakistan" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", flag: "🇱🇰", country: "Sri Lanka" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", flag: "🇧🇩", country: "Bangladesh" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", flag: "🇳🇵", country: "Nepal" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", flag: "🇲🇲", country: "Myanmar" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", flag: "🇰🇭", country: "Cambodia" },
  { code: "LAK", name: "Lao Kip", symbol: "₭", flag: "🇱🇦", country: "Laos" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", flag: "🇻🇳", country: "Vietnam" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", flag: "🇮🇩", country: "Indonesia" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", flag: "🇹🇼", country: "Taiwan" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", flag: "🇰🇿", country: "Kazakhstan" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "лв", flag: "🇺🇿", country: "Uzbekistan" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "лв", flag: "🇰🇬", country: "Kyrgyzstan" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "SM", flag: "🇹🇯", country: "Tajikistan" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "T", flag: "🇹🇲", country: "Turkmenistan" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", flag: "🇦🇫", country: "Afghanistan" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", flag: "🇦🇲", country: "Armenia" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", flag: "🇦🇿", country: "Azerbaijan" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", flag: "🇬🇪", country: "Georgia" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", flag: "🇲🇩", country: "Moldova" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", flag: "🇺🇦", country: "Ukraine" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", flag: "🇧🇾", country: "Belarus" },
  { code: "RSD", name: "Serbian Dinar", symbol: "Дин.", flag: "🇷🇸", country: "Serbia" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", flag: "🇲🇰", country: "North Macedonia" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", flag: "🇦🇱", country: "Albania" },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    symbol: "KM",
    flag: "🇧🇦",
    country: "Bosnia and Herzegovina",
  },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", flag: "🇲🇦", country: "Morocco" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", flag: "🇹🇳", country: "Tunisia" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", flag: "🇩🇿", country: "Algeria" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", flag: "🇱🇾", country: "Libya" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", flag: "🇸🇩", country: "Sudan" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", flag: "🇪🇹", country: "Ethiopia" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", flag: "🇰🇪", country: "Kenya" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", flag: "🇺🇬", country: "Uganda" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", flag: "🇹🇿", country: "Tanzania" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", flag: "🇷🇼", country: "Rwanda" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", flag: "🇧🇮", country: "Burundi" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", flag: "🇩🇯", country: "Djibouti" },
  { code: "SOS", name: "Somali Shilling", symbol: "S", flag: "🇸🇴", country: "Somalia" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", flag: "🇪🇷", country: "Eritrea" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", flag: "🇲🇬", country: "Madagascar" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", flag: "🇲🇺", country: "Mauritius" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", flag: "🇸🇨", country: "Seychelles" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", flag: "🇰🇲", country: "Comoros" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", flag: "🇲🇼", country: "Malawi" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", flag: "🇿🇲", country: "Zambia" },
  { code: "BWP", name: "Botswanan Pula", symbol: "P", flag: "🇧🇼", country: "Botswana" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", flag: "🇸🇿", country: "Eswatini" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", flag: "🇱🇸", country: "Lesotho" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", flag: "🇳🇦", country: "Namibia" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", flag: "🇦🇴", country: "Angola" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", flag: "🇲🇿", country: "Mozambique" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", flag: "🇿🇼", country: "Zimbabwe" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", flag: "🇬🇲", country: "Gambia" },
  { code: "SLE", name: "Sierra Leonean Leone", symbol: "Le", flag: "🇸🇱", country: "Sierra Leone" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", flag: "🇱🇷", country: "Liberia" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", flag: "🇬🇭", country: "Ghana" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", flag: "🇳🇬", country: "Nigeria" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", flag: "🌍", country: "West Africa" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", flag: "🌍", country: "Central Africa" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", flag: "🇨🇻", country: "Cape Verde" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", flag: "🇸🇹", country: "São Tomé and Príncipe" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", flag: "🇬🇳", country: "Guinea" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", flag: "🇨🇩", country: "Democratic Republic of the Congo" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", flag: "🇵🇫", country: "French Polynesia" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", flag: "🇫🇯", country: "Fiji" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", flag: "🇵🇬", country: "Papua New Guinea" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", flag: "🇸🇧", country: "Solomon Islands" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", flag: "🇻🇺", country: "Vanuatu" },
  { code: "WST", name: "Samoan Tala", symbol: "WS$", flag: "🇼🇸", country: "Samoa" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", flag: "🇹🇴", country: "Tonga" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", flag: "🇦🇷", country: "Argentina" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "$b", flag: "🇧🇴", country: "Bolivia" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "Gs", flag: "🇵🇾", country: "Paraguay" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", flag: "🇺🇾", country: "Uruguay" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/.", flag: "🇵🇪", country: "Peru" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs", flag: "🇻🇪", country: "Venezuela" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "GY$", flag: "🇬🇾", country: "Guyana" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "Sr$", flag: "🇸🇷", country: "Suriname" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", flag: "🇹🇹", country: "Trinidad and Tobago" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", flag: "🇯🇲", country: "Jamaica" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", flag: "🇧🇧", country: "Barbados" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", flag: "🇧🇸", country: "Bahamas" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", flag: "🇧🇿", country: "Belize" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", flag: "🇬🇹", country: "Guatemala" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", flag: "🇭🇳", country: "Honduras" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", flag: "🇳🇮", country: "Nicaragua" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", flag: "🇨🇷", country: "Costa Rica" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", flag: "🇵🇦", country: "Panama" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", flag: "🇩🇴", country: "Dominican Republic" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", flag: "🇭🇹", country: "Haiti" },
  { code: "CUP", name: "Cuban Peso", symbol: "₱", flag: "🇨🇺", country: "Cuba" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", flag: "🏴", country: "Eastern Caribbean" },
]

// Helper function to get currency by code
export const getCurrencyByCode = (code: string): CurrencyData | undefined => {
  return CURRENCY_DATA.find((currency) => currency.code === code)
}

// Helper function to get popular currencies for quick access
export const getPopularCurrencies = (): CurrencyData[] => {
  const popularCodes = ["USD", "EUR", "GBP", "JPY", "AUD", "CAD", "CHF", "CNY", "INR", "BRL"]
  return CURRENCY_DATA.filter((currency) => popularCodes.includes(currency.code))
}
